package com.lytrax.accessconverter.report;

import static com.lytrax.accessconverter.report.Severity.ERROR;
import static com.lytrax.accessconverter.report.Severity.INFO;
import static com.lytrax.accessconverter.report.Severity.WARNING;

/** The catalogue of report issues (03). Every data decision that isn't an exact copy raises one of these. */
public enum IssueCode {
    // Source
    CHARSET_UNMAPPED(WARNING),
    CHARSET_OVERRIDDEN(INFO),
    CHARSET_IGNORED(WARNING),
    PASSWORD_NOT_REQUIRED(INFO),
    ROW_ORDER_PHYSICAL(INFO),
    CATALOG_INDEX_UNUSABLE(WARNING),

    // Tables
    LINKED_TABLE_SKIPPED(WARNING),
    LINKED_CONNECTION_PASSWORD(WARNING),
    TABLE_EXCLUDED(INFO),
    TABLE_READ_FAILED(ERROR),
    TABLE_WRITE_FAILED(ERROR),
    TABLE_NOT_IN_CATALOG(ERROR),

    // Keys and indexes
    INDEX_MERGED_DUPLICATE(INFO),
    INDEX_BACKING_DROPPED(INFO),
    UNIQUE_DOWNGRADED_KEY_TOO_LONG(WARNING),
    AUTOINCREMENT_NOT_PRESERVED(WARNING),
    AUTONUMBER_RANDOM_SEQUENTIAL(WARNING),
    AUTONUMBER_RANDOM_DEFAULT(WARNING),
    NO_PRIMARY_KEY(INFO),
    INDEX_SKIPPED_COMPLEX_COLUMN(INFO),
    PARTIAL_INDEX_DROPPED_PARENT_KEY(INFO),
    INDEX_ADDED_FOR_RELATIONSHIP(INFO),
    INDEX_ADDED_FOR_AUTO_INCREMENT(INFO),

    // Relationships
    FK_SKIPPED_NOT_ENFORCED(INFO),
    FK_SKIPPED_ORPHANS(WARNING),
    FK_SKIPPED_PARENT_KEY_MISSING(WARNING),
    FK_SKIPPED_LINKED_TABLE(WARNING),
    FK_SKIPPED_TABLE_EXCLUDED(INFO),
    FK_SET_NULL_ON_REQUIRED(WARNING),
    FK_COLLATION_RELAXED(INFO),
    FK_SKIPPED_TYPE_MISMATCH(WARNING),
    COLLATION_BINARY_KEY(WARNING),
    FOREIGN_KEYS_NEED_PRAGMA(INFO),
    FOREIGN_KEY_CHECK_FAILED(ERROR),
    RELATIONSHIP_MALFORMED(WARNING),
    RELATIONSHIPS_UNREADABLE(ERROR),

    // Columns
    PROPERTIES_UNREADABLE(WARNING),
    UNSUPPORTED_COLUMN_TYPE(WARNING),
    NOT_NULL_DROPPED_NULLS_PRESENT(WARNING),
    DEFAULT_UNTRANSLATABLE(WARNING),
    DEFAULT_DROPPED_TYPE_MISMATCH(WARNING),
    CHECK_UNTRANSLATABLE(WARNING),
    CHECK_VIOLATED_BY_DATA(WARNING),
    TEXT_WIDENED_ROW_SIZE(INFO),
    TABLE_ROW_TOO_LARGE(WARNING),
    CALCULATED_AS_VALUE(INFO),
    IDENTIFIER_RENAMED(INFO),
    COMMENT_TRUNCATED(INFO),
    HIDDEN_COLUMN_SKIPPED(INFO),

    // Conversion
    PROFILE_SKIPPED(INFO),
    VERIFY_DIFFERENCE(ERROR),

    // Values
    VALUE_PRECISION_REDUCED(WARNING),
    DECIMAL_STORED_AS_TEXT(INFO),
    DECIMAL_SCALE_WIDENED(INFO),
    DOUBLE_NON_FINITE(WARNING),
    VALUE_OUT_OF_RANGE(WARNING),
    OLE_UNDECODABLE(WARNING),
    STATEMENT_EXCEEDS_PACKET(WARNING),
    TEXT_UNPAIRED_SURROGATE(WARNING),
    VERSION_HISTORY_SKIPPED(WARNING),
    BINARY_OMITTED(WARNING),
    BINARY_FILES_NOT_REMOVED(ERROR);

    private final Severity severity;

    IssueCode(Severity severity) {
        this.severity = severity;
    }

    public Severity severity() {
        return severity;
    }
}
